// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockusers

import (
	context "context"

	domain "github.com/rom8726/warden/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthProvider is an autogenerated mock type for the AuthProvider type
type MockAuthProvider struct {
	mock.Mock
}

type MockAuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthProvider) EXPECT() *MockAuthProvider_Expecter {
	return &MockAuthProvider_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, username, password
func (_m *MockAuthProvider) Authenticate(ctx context.Context, username string, password string) (*domain.User, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthProvider_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAuthProvider_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAuthProvider_Expecter) Authenticate(ctx interface{}, username interface{}, password interface{}) *MockAuthProvider_Authenticate_Call {
	return &MockAuthProvider_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, username, password)}
}

func (_c *MockAuthProvider_Authenticate_Call) Run(run func(ctx context.Context, username string, password string)) *MockAuthProvider_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthProvider_Authenticate_Call) Return(_a0 *domain.User, _a1 error) *MockAuthProvider_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthProvider_Authenticate_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockAuthProvider_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// CanHandle provides a mock function with given fields: username
func (_m *MockAuthProvider) CanHandle(username string) bool {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for CanHandle")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockAuthProvider_CanHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanHandle'
type MockAuthProvider_CanHandle_Call struct {
	*mock.Call
}

// CanHandle is a helper method to define mock.On call
//   - username string
func (_e *MockAuthProvider_Expecter) CanHandle(username interface{}) *MockAuthProvider_CanHandle_Call {
	return &MockAuthProvider_CanHandle_Call{Call: _e.mock.On("CanHandle", username)}
}

func (_c *MockAuthProvider_CanHandle_Call) Run(run func(username string)) *MockAuthProvider_CanHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthProvider_CanHandle_Call) Return(_a0 bool) *MockAuthProvider_CanHandle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthProvider_CanHandle_Call) RunAndReturn(run func(string) bool) *MockAuthProvider_CanHandle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthProvider creates a new instance of MockAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthProvider {
	mock := &MockAuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
