// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockcontract

import (
	context "context"

	domain "github.com/rom8726/warden/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockProjectsRepository is an autogenerated mock type for the ProjectsRepository type
type MockProjectsRepository struct {
	mock.Mock
}

type MockProjectsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectsRepository) EXPECT() *MockProjectsRepository_Expecter {
	return &MockProjectsRepository_Expecter{mock: &_m.Mock}
}

// GetProjectIDs provides a mock function with given fields: ctx
func (_m *MockProjectsRepository) GetProjectIDs(ctx context.Context) ([]domain.ProjectID, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectIDs")
	}

	var r0 []domain.ProjectID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ProjectID, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ProjectID); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProjectID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectsRepository_GetProjectIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectIDs'
type MockProjectsRepository_GetProjectIDs_Call struct {
	*mock.Call
}

// GetProjectIDs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProjectsRepository_Expecter) GetProjectIDs(ctx interface{}) *MockProjectsRepository_GetProjectIDs_Call {
	return &MockProjectsRepository_GetProjectIDs_Call{Call: _e.mock.On("GetProjectIDs", ctx)}
}

func (_c *MockProjectsRepository_GetProjectIDs_Call) Run(run func(ctx context.Context)) *MockProjectsRepository_GetProjectIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProjectsRepository_GetProjectIDs_Call) Return(_a0 []domain.ProjectID, _a1 error) *MockProjectsRepository_GetProjectIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectsRepository_GetProjectIDs_Call) RunAndReturn(run func(context.Context) ([]domain.ProjectID, error)) *MockProjectsRepository_GetProjectIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateProjectKey provides a mock function with given fields: ctx, projectID, key
func (_m *MockProjectsRepository) ValidateProjectKey(ctx context.Context, projectID domain.ProjectID, key string) (bool, error) {
	ret := _m.Called(ctx, projectID, key)

	if len(ret) == 0 {
		panic("no return value specified for ValidateProjectKey")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProjectID, string) (bool, error)); ok {
		return rf(ctx, projectID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProjectID, string) bool); ok {
		r0 = rf(ctx, projectID, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ProjectID, string) error); ok {
		r1 = rf(ctx, projectID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectsRepository_ValidateProjectKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateProjectKey'
type MockProjectsRepository_ValidateProjectKey_Call struct {
	*mock.Call
}

// ValidateProjectKey is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID domain.ProjectID
//   - key string
func (_e *MockProjectsRepository_Expecter) ValidateProjectKey(ctx interface{}, projectID interface{}, key interface{}) *MockProjectsRepository_ValidateProjectKey_Call {
	return &MockProjectsRepository_ValidateProjectKey_Call{Call: _e.mock.On("ValidateProjectKey", ctx, projectID, key)}
}

func (_c *MockProjectsRepository_ValidateProjectKey_Call) Run(run func(ctx context.Context, projectID domain.ProjectID, key string)) *MockProjectsRepository_ValidateProjectKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ProjectID), args[2].(string))
	})
	return _c
}

func (_c *MockProjectsRepository_ValidateProjectKey_Call) Return(_a0 bool, _a1 error) *MockProjectsRepository_ValidateProjectKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectsRepository_ValidateProjectKey_Call) RunAndReturn(run func(context.Context, domain.ProjectID, string) (bool, error)) *MockProjectsRepository_ValidateProjectKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectsRepository creates a new instance of MockProjectsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectsRepository {
	mock := &MockProjectsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
