// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockcontract

import (
	context "context"

	domain "github.com/rom8726/warden/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockStoreEventUseCase is an autogenerated mock type for the StoreEventUseCase type
type MockStoreEventUseCase struct {
	mock.Mock
}

type MockStoreEventUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreEventUseCase) EXPECT() *MockStoreEventUseCase_Expecter {
	return &MockStoreEventUseCase_Expecter{mock: &_m.Mock}
}

// StoreEvent provides a mock function with given fields: ctx, projectID, req
func (_m *MockStoreEventUseCase) StoreEvent(ctx context.Context, projectID domain.ProjectID, req map[string]interface{}) (domain.EventID, error) {
	ret := _m.Called(ctx, projectID, req)

	if len(ret) == 0 {
		panic("no return value specified for StoreEvent")
	}

	var r0 domain.EventID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProjectID, map[string]interface{}) (domain.EventID, error)); ok {
		return rf(ctx, projectID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProjectID, map[string]interface{}) domain.EventID); ok {
		r0 = rf(ctx, projectID, req)
	} else {
		r0 = ret.Get(0).(domain.EventID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ProjectID, map[string]interface{}) error); ok {
		r1 = rf(ctx, projectID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoreEventUseCase_StoreEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreEvent'
type MockStoreEventUseCase_StoreEvent_Call struct {
	*mock.Call
}

// StoreEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID domain.ProjectID
//   - req map[string]interface{}
func (_e *MockStoreEventUseCase_Expecter) StoreEvent(ctx interface{}, projectID interface{}, req interface{}) *MockStoreEventUseCase_StoreEvent_Call {
	return &MockStoreEventUseCase_StoreEvent_Call{Call: _e.mock.On("StoreEvent", ctx, projectID, req)}
}

func (_c *MockStoreEventUseCase_StoreEvent_Call) Run(run func(ctx context.Context, projectID domain.ProjectID, req map[string]interface{})) *MockStoreEventUseCase_StoreEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ProjectID), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockStoreEventUseCase_StoreEvent_Call) Return(_a0 domain.EventID, _a1 error) *MockStoreEventUseCase_StoreEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoreEventUseCase_StoreEvent_Call) RunAndReturn(run func(context.Context, domain.ProjectID, map[string]interface{}) (domain.EventID, error)) *MockStoreEventUseCase_StoreEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStoreEventUseCase creates a new instance of MockStoreEventUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreEventUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreEventUseCase {
	mock := &MockStoreEventUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
