// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockcontract

import (
	context "context"

	domain "github.com/rom8726/warden/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockUserNotificationsUseCase is an autogenerated mock type for the UserNotificationsUseCase type
type MockUserNotificationsUseCase struct {
	mock.Mock
}

type MockUserNotificationsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserNotificationsUseCase) EXPECT() *MockUserNotificationsUseCase_Expecter {
	return &MockUserNotificationsUseCase_Expecter{mock: &_m.Mock}
}

// CreateNotification provides a mock function with given fields: ctx, userID, notificationType, content
func (_m *MockUserNotificationsUseCase) CreateNotification(ctx context.Context, userID domain.UserID, notificationType domain.UserNotificationType, content domain.UserNotificationContent) error {
	ret := _m.Called(ctx, userID, notificationType, content)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.UserNotificationType, domain.UserNotificationContent) error); ok {
		r0 = rf(ctx, userID, notificationType, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserNotificationsUseCase_CreateNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotification'
type MockUserNotificationsUseCase_CreateNotification_Call struct {
	*mock.Call
}

// CreateNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - notificationType domain.UserNotificationType
//   - content domain.UserNotificationContent
func (_e *MockUserNotificationsUseCase_Expecter) CreateNotification(ctx interface{}, userID interface{}, notificationType interface{}, content interface{}) *MockUserNotificationsUseCase_CreateNotification_Call {
	return &MockUserNotificationsUseCase_CreateNotification_Call{Call: _e.mock.On("CreateNotification", ctx, userID, notificationType, content)}
}

func (_c *MockUserNotificationsUseCase_CreateNotification_Call) Run(run func(ctx context.Context, userID domain.UserID, notificationType domain.UserNotificationType, content domain.UserNotificationContent)) *MockUserNotificationsUseCase_CreateNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID), args[2].(domain.UserNotificationType), args[3].(domain.UserNotificationContent))
	})
	return _c
}

func (_c *MockUserNotificationsUseCase_CreateNotification_Call) Return(_a0 error) *MockUserNotificationsUseCase_CreateNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserNotificationsUseCase_CreateNotification_Call) RunAndReturn(run func(context.Context, domain.UserID, domain.UserNotificationType, domain.UserNotificationContent) error) *MockUserNotificationsUseCase_CreateNotification_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOldNotifications provides a mock function with given fields: ctx, maxAge, limit
func (_m *MockUserNotificationsUseCase) DeleteOldNotifications(ctx context.Context, maxAge time.Duration, limit uint) (uint, error) {
	ret := _m.Called(ctx, maxAge, limit)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldNotifications")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration, uint) (uint, error)); ok {
		return rf(ctx, maxAge, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration, uint) uint); ok {
		r0 = rf(ctx, maxAge, limit)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration, uint) error); ok {
		r1 = rf(ctx, maxAge, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserNotificationsUseCase_DeleteOldNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOldNotifications'
type MockUserNotificationsUseCase_DeleteOldNotifications_Call struct {
	*mock.Call
}

// DeleteOldNotifications is a helper method to define mock.On call
//   - ctx context.Context
//   - maxAge time.Duration
//   - limit uint
func (_e *MockUserNotificationsUseCase_Expecter) DeleteOldNotifications(ctx interface{}, maxAge interface{}, limit interface{}) *MockUserNotificationsUseCase_DeleteOldNotifications_Call {
	return &MockUserNotificationsUseCase_DeleteOldNotifications_Call{Call: _e.mock.On("DeleteOldNotifications", ctx, maxAge, limit)}
}

func (_c *MockUserNotificationsUseCase_DeleteOldNotifications_Call) Run(run func(ctx context.Context, maxAge time.Duration, limit uint)) *MockUserNotificationsUseCase_DeleteOldNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration), args[2].(uint))
	})
	return _c
}

func (_c *MockUserNotificationsUseCase_DeleteOldNotifications_Call) Return(_a0 uint, _a1 error) *MockUserNotificationsUseCase_DeleteOldNotifications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserNotificationsUseCase_DeleteOldNotifications_Call) RunAndReturn(run func(context.Context, time.Duration, uint) (uint, error)) *MockUserNotificationsUseCase_DeleteOldNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnreadCount provides a mock function with given fields: ctx, userID
func (_m *MockUserNotificationsUseCase) GetUnreadCount(ctx context.Context, userID domain.UserID) (uint, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadCount")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID) (uint, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID) uint); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserNotificationsUseCase_GetUnreadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnreadCount'
type MockUserNotificationsUseCase_GetUnreadCount_Call struct {
	*mock.Call
}

// GetUnreadCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
func (_e *MockUserNotificationsUseCase_Expecter) GetUnreadCount(ctx interface{}, userID interface{}) *MockUserNotificationsUseCase_GetUnreadCount_Call {
	return &MockUserNotificationsUseCase_GetUnreadCount_Call{Call: _e.mock.On("GetUnreadCount", ctx, userID)}
}

func (_c *MockUserNotificationsUseCase_GetUnreadCount_Call) Run(run func(ctx context.Context, userID domain.UserID)) *MockUserNotificationsUseCase_GetUnreadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID))
	})
	return _c
}

func (_c *MockUserNotificationsUseCase_GetUnreadCount_Call) Return(_a0 uint, _a1 error) *MockUserNotificationsUseCase_GetUnreadCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserNotificationsUseCase_GetUnreadCount_Call) RunAndReturn(run func(context.Context, domain.UserID) (uint, error)) *MockUserNotificationsUseCase_GetUnreadCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserNotifications provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockUserNotificationsUseCase) GetUserNotifications(ctx context.Context, userID domain.UserID, limit uint, offset uint) ([]domain.UserNotification, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserNotifications")
	}

	var r0 []domain.UserNotification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID, uint, uint) ([]domain.UserNotification, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID, uint, uint) []domain.UserNotification); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserNotification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserID, uint, uint) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserNotificationsUseCase_GetUserNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserNotifications'
type MockUserNotificationsUseCase_GetUserNotifications_Call struct {
	*mock.Call
}

// GetUserNotifications is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - limit uint
//   - offset uint
func (_e *MockUserNotificationsUseCase_Expecter) GetUserNotifications(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockUserNotificationsUseCase_GetUserNotifications_Call {
	return &MockUserNotificationsUseCase_GetUserNotifications_Call{Call: _e.mock.On("GetUserNotifications", ctx, userID, limit, offset)}
}

func (_c *MockUserNotificationsUseCase_GetUserNotifications_Call) Run(run func(ctx context.Context, userID domain.UserID, limit uint, offset uint)) *MockUserNotificationsUseCase_GetUserNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID), args[2].(uint), args[3].(uint))
	})
	return _c
}

func (_c *MockUserNotificationsUseCase_GetUserNotifications_Call) Return(_a0 []domain.UserNotification, _a1 error) *MockUserNotificationsUseCase_GetUserNotifications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserNotificationsUseCase_GetUserNotifications_Call) RunAndReturn(run func(context.Context, domain.UserID, uint, uint) ([]domain.UserNotification, error)) *MockUserNotificationsUseCase_GetUserNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllAsRead provides a mock function with given fields: ctx, userID
func (_m *MockUserNotificationsUseCase) MarkAllAsRead(ctx context.Context, userID domain.UserID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserNotificationsUseCase_MarkAllAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllAsRead'
type MockUserNotificationsUseCase_MarkAllAsRead_Call struct {
	*mock.Call
}

// MarkAllAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
func (_e *MockUserNotificationsUseCase_Expecter) MarkAllAsRead(ctx interface{}, userID interface{}) *MockUserNotificationsUseCase_MarkAllAsRead_Call {
	return &MockUserNotificationsUseCase_MarkAllAsRead_Call{Call: _e.mock.On("MarkAllAsRead", ctx, userID)}
}

func (_c *MockUserNotificationsUseCase_MarkAllAsRead_Call) Run(run func(ctx context.Context, userID domain.UserID)) *MockUserNotificationsUseCase_MarkAllAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID))
	})
	return _c
}

func (_c *MockUserNotificationsUseCase_MarkAllAsRead_Call) Return(_a0 error) *MockUserNotificationsUseCase_MarkAllAsRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserNotificationsUseCase_MarkAllAsRead_Call) RunAndReturn(run func(context.Context, domain.UserID) error) *MockUserNotificationsUseCase_MarkAllAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsRead provides a mock function with given fields: ctx, notificationID
func (_m *MockUserNotificationsUseCase) MarkAsRead(ctx context.Context, notificationID domain.UserNotificationID) error {
	ret := _m.Called(ctx, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserNotificationID) error); ok {
		r0 = rf(ctx, notificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserNotificationsUseCase_MarkAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsRead'
type MockUserNotificationsUseCase_MarkAsRead_Call struct {
	*mock.Call
}

// MarkAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationID domain.UserNotificationID
func (_e *MockUserNotificationsUseCase_Expecter) MarkAsRead(ctx interface{}, notificationID interface{}) *MockUserNotificationsUseCase_MarkAsRead_Call {
	return &MockUserNotificationsUseCase_MarkAsRead_Call{Call: _e.mock.On("MarkAsRead", ctx, notificationID)}
}

func (_c *MockUserNotificationsUseCase_MarkAsRead_Call) Run(run func(ctx context.Context, notificationID domain.UserNotificationID)) *MockUserNotificationsUseCase_MarkAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserNotificationID))
	})
	return _c
}

func (_c *MockUserNotificationsUseCase_MarkAsRead_Call) Return(_a0 error) *MockUserNotificationsUseCase_MarkAsRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserNotificationsUseCase_MarkAsRead_Call) RunAndReturn(run func(context.Context, domain.UserNotificationID) error) *MockUserNotificationsUseCase_MarkAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserNotificationsUseCase creates a new instance of MockUserNotificationsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserNotificationsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserNotificationsUseCase {
	mock := &MockUserNotificationsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
