// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockcontract

import (
	context "context"

	domain "github.com/rom8726/warden/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockTeamsUseCase is an autogenerated mock type for the TeamsUseCase type
type MockTeamsUseCase struct {
	mock.Mock
}

type MockTeamsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamsUseCase) EXPECT() *MockTeamsUseCase_Expecter {
	return &MockTeamsUseCase_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, teamID, userID, role
func (_m *MockTeamsUseCase) AddMember(ctx context.Context, teamID domain.TeamID, userID domain.UserID, role domain.Role) error {
	ret := _m.Called(ctx, teamID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamID, domain.UserID, domain.Role) error); ok {
		r0 = rf(ctx, teamID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamsUseCase_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockTeamsUseCase_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID domain.TeamID
//   - userID domain.UserID
//   - role domain.Role
func (_e *MockTeamsUseCase_Expecter) AddMember(ctx interface{}, teamID interface{}, userID interface{}, role interface{}) *MockTeamsUseCase_AddMember_Call {
	return &MockTeamsUseCase_AddMember_Call{Call: _e.mock.On("AddMember", ctx, teamID, userID, role)}
}

func (_c *MockTeamsUseCase_AddMember_Call) Run(run func(ctx context.Context, teamID domain.TeamID, userID domain.UserID, role domain.Role)) *MockTeamsUseCase_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TeamID), args[2].(domain.UserID), args[3].(domain.Role))
	})
	return _c
}

func (_c *MockTeamsUseCase_AddMember_Call) Return(_a0 error) *MockTeamsUseCase_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamsUseCase_AddMember_Call) RunAndReturn(run func(context.Context, domain.TeamID, domain.UserID, domain.Role) error) *MockTeamsUseCase_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeMemberRole provides a mock function with given fields: ctx, teamID, userID, newRole
func (_m *MockTeamsUseCase) ChangeMemberRole(ctx context.Context, teamID domain.TeamID, userID domain.UserID, newRole domain.Role) error {
	ret := _m.Called(ctx, teamID, userID, newRole)

	if len(ret) == 0 {
		panic("no return value specified for ChangeMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamID, domain.UserID, domain.Role) error); ok {
		r0 = rf(ctx, teamID, userID, newRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamsUseCase_ChangeMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeMemberRole'
type MockTeamsUseCase_ChangeMemberRole_Call struct {
	*mock.Call
}

// ChangeMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID domain.TeamID
//   - userID domain.UserID
//   - newRole domain.Role
func (_e *MockTeamsUseCase_Expecter) ChangeMemberRole(ctx interface{}, teamID interface{}, userID interface{}, newRole interface{}) *MockTeamsUseCase_ChangeMemberRole_Call {
	return &MockTeamsUseCase_ChangeMemberRole_Call{Call: _e.mock.On("ChangeMemberRole", ctx, teamID, userID, newRole)}
}

func (_c *MockTeamsUseCase_ChangeMemberRole_Call) Run(run func(ctx context.Context, teamID domain.TeamID, userID domain.UserID, newRole domain.Role)) *MockTeamsUseCase_ChangeMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TeamID), args[2].(domain.UserID), args[3].(domain.Role))
	})
	return _c
}

func (_c *MockTeamsUseCase_ChangeMemberRole_Call) Return(_a0 error) *MockTeamsUseCase_ChangeMemberRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamsUseCase_ChangeMemberRole_Call) RunAndReturn(run func(context.Context, domain.TeamID, domain.UserID, domain.Role) error) *MockTeamsUseCase_ChangeMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, teamDTO
func (_m *MockTeamsUseCase) Create(ctx context.Context, teamDTO domain.TeamDTO) (domain.Team, error) {
	ret := _m.Called(ctx, teamDTO)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamDTO) (domain.Team, error)); ok {
		return rf(ctx, teamDTO)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamDTO) domain.Team); ok {
		r0 = rf(ctx, teamDTO)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TeamDTO) error); ok {
		r1 = rf(ctx, teamDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamsUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeamsUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - teamDTO domain.TeamDTO
func (_e *MockTeamsUseCase_Expecter) Create(ctx interface{}, teamDTO interface{}) *MockTeamsUseCase_Create_Call {
	return &MockTeamsUseCase_Create_Call{Call: _e.mock.On("Create", ctx, teamDTO)}
}

func (_c *MockTeamsUseCase_Create_Call) Run(run func(ctx context.Context, teamDTO domain.TeamDTO)) *MockTeamsUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TeamDTO))
	})
	return _c
}

func (_c *MockTeamsUseCase_Create_Call) Return(_a0 domain.Team, _a1 error) *MockTeamsUseCase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamsUseCase_Create_Call) RunAndReturn(run func(context.Context, domain.TeamDTO) (domain.Team, error)) *MockTeamsUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTeamsUseCase) Delete(ctx context.Context, id domain.TeamID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamsUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTeamsUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.TeamID
func (_e *MockTeamsUseCase_Expecter) Delete(ctx interface{}, id interface{}) *MockTeamsUseCase_Delete_Call {
	return &MockTeamsUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTeamsUseCase_Delete_Call) Run(run func(ctx context.Context, id domain.TeamID)) *MockTeamsUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TeamID))
	})
	return _c
}

func (_c *MockTeamsUseCase_Delete_Call) Return(_a0 error) *MockTeamsUseCase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamsUseCase_Delete_Call) RunAndReturn(run func(context.Context, domain.TeamID) error) *MockTeamsUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTeamsUseCase) GetByID(ctx context.Context, id domain.TeamID) (domain.Team, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamID) (domain.Team, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamID) domain.Team); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TeamID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamsUseCase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTeamsUseCase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.TeamID
func (_e *MockTeamsUseCase_Expecter) GetByID(ctx interface{}, id interface{}) *MockTeamsUseCase_GetByID_Call {
	return &MockTeamsUseCase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTeamsUseCase_GetByID_Call) Run(run func(ctx context.Context, id domain.TeamID)) *MockTeamsUseCase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TeamID))
	})
	return _c
}

func (_c *MockTeamsUseCase_GetByID_Call) Return(_a0 domain.Team, _a1 error) *MockTeamsUseCase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamsUseCase_GetByID_Call) RunAndReturn(run func(context.Context, domain.TeamID) (domain.Team, error)) *MockTeamsUseCase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockTeamsUseCase) GetByName(ctx context.Context, name string) (domain.Team, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Team, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Team); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamsUseCase_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTeamsUseCase_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamsUseCase_Expecter) GetByName(ctx interface{}, name interface{}) *MockTeamsUseCase_GetByName_Call {
	return &MockTeamsUseCase_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockTeamsUseCase_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockTeamsUseCase_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamsUseCase_GetByName_Call) Return(_a0 domain.Team, _a1 error) *MockTeamsUseCase_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamsUseCase_GetByName_Call) RunAndReturn(run func(context.Context, string) (domain.Team, error)) *MockTeamsUseCase_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProjectID provides a mock function with given fields: ctx, projectID
func (_m *MockTeamsUseCase) GetByProjectID(ctx context.Context, projectID domain.ProjectID) (domain.Team, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProjectID")
	}

	var r0 domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProjectID) (domain.Team, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProjectID) domain.Team); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ProjectID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamsUseCase_GetByProjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProjectID'
type MockTeamsUseCase_GetByProjectID_Call struct {
	*mock.Call
}

// GetByProjectID is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID domain.ProjectID
func (_e *MockTeamsUseCase_Expecter) GetByProjectID(ctx interface{}, projectID interface{}) *MockTeamsUseCase_GetByProjectID_Call {
	return &MockTeamsUseCase_GetByProjectID_Call{Call: _e.mock.On("GetByProjectID", ctx, projectID)}
}

func (_c *MockTeamsUseCase_GetByProjectID_Call) Run(run func(ctx context.Context, projectID domain.ProjectID)) *MockTeamsUseCase_GetByProjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ProjectID))
	})
	return _c
}

func (_c *MockTeamsUseCase_GetByProjectID_Call) Return(_a0 domain.Team, _a1 error) *MockTeamsUseCase_GetByProjectID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamsUseCase_GetByProjectID_Call) RunAndReturn(run func(context.Context, domain.ProjectID) (domain.Team, error)) *MockTeamsUseCase_GetByProjectID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembers provides a mock function with given fields: ctx, teamID
func (_m *MockTeamsUseCase) GetMembers(ctx context.Context, teamID domain.TeamID) ([]domain.TeamMember, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []domain.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamID) ([]domain.TeamMember, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamID) []domain.TeamMember); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TeamID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamsUseCase_GetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembers'
type MockTeamsUseCase_GetMembers_Call struct {
	*mock.Call
}

// GetMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID domain.TeamID
func (_e *MockTeamsUseCase_Expecter) GetMembers(ctx interface{}, teamID interface{}) *MockTeamsUseCase_GetMembers_Call {
	return &MockTeamsUseCase_GetMembers_Call{Call: _e.mock.On("GetMembers", ctx, teamID)}
}

func (_c *MockTeamsUseCase_GetMembers_Call) Run(run func(ctx context.Context, teamID domain.TeamID)) *MockTeamsUseCase_GetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TeamID))
	})
	return _c
}

func (_c *MockTeamsUseCase_GetMembers_Call) Return(_a0 []domain.TeamMember, _a1 error) *MockTeamsUseCase_GetMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamsUseCase_GetMembers_Call) RunAndReturn(run func(context.Context, domain.TeamID) ([]domain.TeamMember, error)) *MockTeamsUseCase_GetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamByID provides a mock function with given fields: ctx, id
func (_m *MockTeamsUseCase) GetTeamByID(ctx context.Context, id domain.TeamID) (domain.Team, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByID")
	}

	var r0 domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamID) (domain.Team, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamID) domain.Team); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TeamID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamsUseCase_GetTeamByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamByID'
type MockTeamsUseCase_GetTeamByID_Call struct {
	*mock.Call
}

// GetTeamByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.TeamID
func (_e *MockTeamsUseCase_Expecter) GetTeamByID(ctx interface{}, id interface{}) *MockTeamsUseCase_GetTeamByID_Call {
	return &MockTeamsUseCase_GetTeamByID_Call{Call: _e.mock.On("GetTeamByID", ctx, id)}
}

func (_c *MockTeamsUseCase_GetTeamByID_Call) Run(run func(ctx context.Context, id domain.TeamID)) *MockTeamsUseCase_GetTeamByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TeamID))
	})
	return _c
}

func (_c *MockTeamsUseCase_GetTeamByID_Call) Return(_a0 domain.Team, _a1 error) *MockTeamsUseCase_GetTeamByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamsUseCase_GetTeamByID_Call) RunAndReturn(run func(context.Context, domain.TeamID) (domain.Team, error)) *MockTeamsUseCase_GetTeamByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockTeamsUseCase) GetTeamsByUserID(ctx context.Context, userID domain.UserID) ([]domain.Team, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamsByUserID")
	}

	var r0 []domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID) ([]domain.Team, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID) []domain.Team); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamsUseCase_GetTeamsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamsByUserID'
type MockTeamsUseCase_GetTeamsByUserID_Call struct {
	*mock.Call
}

// GetTeamsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
func (_e *MockTeamsUseCase_Expecter) GetTeamsByUserID(ctx interface{}, userID interface{}) *MockTeamsUseCase_GetTeamsByUserID_Call {
	return &MockTeamsUseCase_GetTeamsByUserID_Call{Call: _e.mock.On("GetTeamsByUserID", ctx, userID)}
}

func (_c *MockTeamsUseCase_GetTeamsByUserID_Call) Run(run func(ctx context.Context, userID domain.UserID)) *MockTeamsUseCase_GetTeamsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID))
	})
	return _c
}

func (_c *MockTeamsUseCase_GetTeamsByUserID_Call) Return(_a0 []domain.Team, _a1 error) *MockTeamsUseCase_GetTeamsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamsUseCase_GetTeamsByUserID_Call) RunAndReturn(run func(context.Context, domain.UserID) ([]domain.Team, error)) *MockTeamsUseCase_GetTeamsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockTeamsUseCase) List(ctx context.Context) ([]domain.Team, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Team, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Team); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamsUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTeamsUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTeamsUseCase_Expecter) List(ctx interface{}) *MockTeamsUseCase_List_Call {
	return &MockTeamsUseCase_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTeamsUseCase_List_Call) Run(run func(ctx context.Context)) *MockTeamsUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTeamsUseCase_List_Call) Return(_a0 []domain.Team, _a1 error) *MockTeamsUseCase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamsUseCase_List_Call) RunAndReturn(run func(context.Context) ([]domain.Team, error)) *MockTeamsUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMemberWithChecks provides a mock function with given fields: ctx, teamID, userID
func (_m *MockTeamsUseCase) RemoveMemberWithChecks(ctx context.Context, teamID domain.TeamID, userID domain.UserID) error {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMemberWithChecks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TeamID, domain.UserID) error); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamsUseCase_RemoveMemberWithChecks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMemberWithChecks'
type MockTeamsUseCase_RemoveMemberWithChecks_Call struct {
	*mock.Call
}

// RemoveMemberWithChecks is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID domain.TeamID
//   - userID domain.UserID
func (_e *MockTeamsUseCase_Expecter) RemoveMemberWithChecks(ctx interface{}, teamID interface{}, userID interface{}) *MockTeamsUseCase_RemoveMemberWithChecks_Call {
	return &MockTeamsUseCase_RemoveMemberWithChecks_Call{Call: _e.mock.On("RemoveMemberWithChecks", ctx, teamID, userID)}
}

func (_c *MockTeamsUseCase_RemoveMemberWithChecks_Call) Run(run func(ctx context.Context, teamID domain.TeamID, userID domain.UserID)) *MockTeamsUseCase_RemoveMemberWithChecks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TeamID), args[2].(domain.UserID))
	})
	return _c
}

func (_c *MockTeamsUseCase_RemoveMemberWithChecks_Call) Return(_a0 error) *MockTeamsUseCase_RemoveMemberWithChecks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamsUseCase_RemoveMemberWithChecks_Call) RunAndReturn(run func(context.Context, domain.TeamID, domain.UserID) error) *MockTeamsUseCase_RemoveMemberWithChecks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamsUseCase creates a new instance of MockTeamsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamsUseCase {
	mock := &MockTeamsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
