// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockcontract

import (
	context "context"

	contract "github.com/rom8726/warden/internal/backend/contract"
	mock "github.com/stretchr/testify/mock"
)

// MockVersionsUseCase is an autogenerated mock type for the VersionsUseCase type
type MockVersionsUseCase struct {
	mock.Mock
}

type MockVersionsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionsUseCase) EXPECT() *MockVersionsUseCase_Expecter {
	return &MockVersionsUseCase_Expecter{mock: &_m.Mock}
}

// GetVersions provides a mock function with given fields: ctx
func (_m *MockVersionsUseCase) GetVersions(ctx context.Context) ([]contract.ComponentVersion, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetVersions")
	}

	var r0 []contract.ComponentVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]contract.ComponentVersion, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []contract.ComponentVersion); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contract.ComponentVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersionsUseCase_GetVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersions'
type MockVersionsUseCase_GetVersions_Call struct {
	*mock.Call
}

// GetVersions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVersionsUseCase_Expecter) GetVersions(ctx interface{}) *MockVersionsUseCase_GetVersions_Call {
	return &MockVersionsUseCase_GetVersions_Call{Call: _e.mock.On("GetVersions", ctx)}
}

func (_c *MockVersionsUseCase_GetVersions_Call) Run(run func(ctx context.Context)) *MockVersionsUseCase_GetVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockVersionsUseCase_GetVersions_Call) Return(_a0 []contract.ComponentVersion, _a1 error) *MockVersionsUseCase_GetVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersionsUseCase_GetVersions_Call) RunAndReturn(run func(context.Context) ([]contract.ComponentVersion, error)) *MockVersionsUseCase_GetVersions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVersionsUseCase creates a new instance of MockVersionsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionsUseCase {
	mock := &MockVersionsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
