// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockcontract

import (
	context "context"

	domain "github.com/rom8726/warden/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockProjectsRepository is an autogenerated mock type for the ProjectsRepository type
type MockProjectsRepository struct {
	mock.Mock
}

type MockProjectsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectsRepository) EXPECT() *MockProjectsRepository_Expecter {
	return &MockProjectsRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockProjectsRepository) GetByID(ctx context.Context, id domain.ProjectID) (domain.Project, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProjectID) (domain.Project, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProjectID) domain.Project); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ProjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectsRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProjectsRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ProjectID
func (_e *MockProjectsRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockProjectsRepository_GetByID_Call {
	return &MockProjectsRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProjectsRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.ProjectID)) *MockProjectsRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ProjectID))
	})
	return _c
}

func (_c *MockProjectsRepository_GetByID_Call) Return(_a0 domain.Project, _a1 error) *MockProjectsRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectsRepository_GetByID_Call) RunAndReturn(run func(context.Context, domain.ProjectID) (domain.Project, error)) *MockProjectsRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockProjectsRepository) List(ctx context.Context) ([]domain.ProjectExtended, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.ProjectExtended
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ProjectExtended, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ProjectExtended); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProjectExtended)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectsRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProjectsRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProjectsRepository_Expecter) List(ctx interface{}) *MockProjectsRepository_List_Call {
	return &MockProjectsRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockProjectsRepository_List_Call) Run(run func(ctx context.Context)) *MockProjectsRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProjectsRepository_List_Call) Return(_a0 []domain.ProjectExtended, _a1 error) *MockProjectsRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectsRepository_List_Call) RunAndReturn(run func(context.Context) ([]domain.ProjectExtended, error)) *MockProjectsRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectsRepository creates a new instance of MockProjectsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectsRepository {
	mock := &MockProjectsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
