// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockcontract

import (
	context "context"

	domain "github.com/rom8726/warden/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockReleaseStatsRepository is an autogenerated mock type for the ReleaseStatsRepository type
type MockReleaseStatsRepository struct {
	mock.Mock
}

type MockReleaseStatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReleaseStatsRepository) EXPECT() *MockReleaseStatsRepository_Expecter {
	return &MockReleaseStatsRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, stats
func (_m *MockReleaseStatsRepository) Create(ctx context.Context, stats domain.ReleaseStats) error {
	ret := _m.Called(ctx, stats)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ReleaseStats) error); ok {
		r0 = rf(ctx, stats)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReleaseStatsRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReleaseStatsRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - stats domain.ReleaseStats
func (_e *MockReleaseStatsRepository_Expecter) Create(ctx interface{}, stats interface{}) *MockReleaseStatsRepository_Create_Call {
	return &MockReleaseStatsRepository_Create_Call{Call: _e.mock.On("Create", ctx, stats)}
}

func (_c *MockReleaseStatsRepository_Create_Call) Run(run func(ctx context.Context, stats domain.ReleaseStats)) *MockReleaseStatsRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ReleaseStats))
	})
	return _c
}

func (_c *MockReleaseStatsRepository_Create_Call) Return(_a0 error) *MockReleaseStatsRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReleaseStatsRepository_Create_Call) RunAndReturn(run func(context.Context, domain.ReleaseStats) error) *MockReleaseStatsRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReleaseStatsRepository creates a new instance of MockReleaseStatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReleaseStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReleaseStatsRepository {
	mock := &MockReleaseStatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
