// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockcontract

import (
	context "context"

	domain "github.com/rom8726/warden/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockReleaseRepository is an autogenerated mock type for the ReleaseRepository type
type MockReleaseRepository struct {
	mock.Mock
}

type MockReleaseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReleaseRepository) EXPECT() *MockReleaseRepository_Expecter {
	return &MockReleaseRepository_Expecter{mock: &_m.Mock}
}

// ListByProject provides a mock function with given fields: ctx, projectID
func (_m *MockReleaseRepository) ListByProject(ctx context.Context, projectID domain.ProjectID) ([]domain.Release, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListByProject")
	}

	var r0 []domain.Release
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProjectID) ([]domain.Release, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProjectID) []domain.Release); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Release)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ProjectID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReleaseRepository_ListByProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByProject'
type MockReleaseRepository_ListByProject_Call struct {
	*mock.Call
}

// ListByProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID domain.ProjectID
func (_e *MockReleaseRepository_Expecter) ListByProject(ctx interface{}, projectID interface{}) *MockReleaseRepository_ListByProject_Call {
	return &MockReleaseRepository_ListByProject_Call{Call: _e.mock.On("ListByProject", ctx, projectID)}
}

func (_c *MockReleaseRepository_ListByProject_Call) Run(run func(ctx context.Context, projectID domain.ProjectID)) *MockReleaseRepository_ListByProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ProjectID))
	})
	return _c
}

func (_c *MockReleaseRepository_ListByProject_Call) Return(_a0 []domain.Release, _a1 error) *MockReleaseRepository_ListByProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReleaseRepository_ListByProject_Call) RunAndReturn(run func(context.Context, domain.ProjectID) ([]domain.Release, error)) *MockReleaseRepository_ListByProject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReleaseRepository creates a new instance of MockReleaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReleaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReleaseRepository {
	mock := &MockReleaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
