// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockcontract

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAnalyticsUseCase is an autogenerated mock type for the AnalyticsUseCase type
type MockAnalyticsUseCase struct {
	mock.Mock
}

type MockAnalyticsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsUseCase) EXPECT() *MockAnalyticsUseCase_Expecter {
	return &MockAnalyticsUseCase_Expecter{mock: &_m.Mock}
}

// RecalculateReleaseStatsForAllProjects provides a mock function with given fields: ctx
func (_m *MockAnalyticsUseCase) RecalculateReleaseStatsForAllProjects(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RecalculateReleaseStatsForAllProjects")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnalyticsUseCase_RecalculateReleaseStatsForAllProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecalculateReleaseStatsForAllProjects'
type MockAnalyticsUseCase_RecalculateReleaseStatsForAllProjects_Call struct {
	*mock.Call
}

// RecalculateReleaseStatsForAllProjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAnalyticsUseCase_Expecter) RecalculateReleaseStatsForAllProjects(ctx interface{}) *MockAnalyticsUseCase_RecalculateReleaseStatsForAllProjects_Call {
	return &MockAnalyticsUseCase_RecalculateReleaseStatsForAllProjects_Call{Call: _e.mock.On("RecalculateReleaseStatsForAllProjects", ctx)}
}

func (_c *MockAnalyticsUseCase_RecalculateReleaseStatsForAllProjects_Call) Run(run func(ctx context.Context)) *MockAnalyticsUseCase_RecalculateReleaseStatsForAllProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAnalyticsUseCase_RecalculateReleaseStatsForAllProjects_Call) Return(_a0 error) *MockAnalyticsUseCase_RecalculateReleaseStatsForAllProjects_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnalyticsUseCase_RecalculateReleaseStatsForAllProjects_Call) RunAndReturn(run func(context.Context) error) *MockAnalyticsUseCase_RecalculateReleaseStatsForAllProjects_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnalyticsUseCase creates a new instance of MockAnalyticsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsUseCase {
	mock := &MockAnalyticsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
